### ISSUE TITLE
Added new SSH key on Github, but could not get Windows 10 WSL bash git to clone from SSH

### ISSUE THREAD

**Issue by maxloopinmok** [maxloosmu/haskellbook#1]
On my Windows 10 PC, I created a new SSH key using ssh-keygen on cmd platform.  The key is password protected.  Using WSL bash, I copied the SSH files to ~/.ssh/id_rsa/.  I also added the SSH key to Github's "SSH and GPG keys" section.  However, when I tried on WSL bash: 

git clone git@github.com:maxloosmu/haskellbook.git

I get the error:
```
WARNING: UNPROTECTED PRIVATE KEY FILE
Permissions 0755 for '/home/maxloo/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/home/maxloo/.ssh/id_rsa": bad permissions
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

```

How do I clone my repository using SSH?  Will I need to clone my repository in order to pull from it?  I'm asking this because I'm using 2 PCs to access the same repository, and would like to push from the repository using PC A, and pull from the repository using the PC B.  I may also swap the roles of both PCs, pushing using PC B, and pulling using PC A.  Is this approach doable?

**Comment by mengwong** [comment]
My `.ssh` directory may be a useful comparison:

```
┌─[mengwong@solo-wmw] - [~/.ssh] - [2021-02-09 06:49:04]
└─[0] <> ll
total 128
-rw-------  1 mengwong  staff   404B Jun 22  2020 authorized_keys
-rw-------  1 mengwong  staff   1.7K Jun 22  2020 aws-cclaw-2.pem
-rw-r--r--  1 mengwong  staff   6.0K Aug 24 20:21 config
-rw-------  1 mengwong  staff   1.7K Dec  3 20:25 foscari2.pem
-rw-------  1 mengwong  staff   2.6K Nov  3 15:57 id_2
-rw-r--r--  1 mengwong  staff   571B Nov  3 15:57 id_2.pub
-rw-------  1 mengwong  staff   2.6K Aug 19 15:18 id_cclaw_rsa
-rw-r--r--  1 mengwong  staff   571B Aug 19 15:18 id_cclaw_rsa.pub
-rw-------  1 mengwong  staff   1.6K Jun 23  2020 id_git_rsa
-rw-------  1 mengwong  staff   2.5K Jun 22  2020 id_rsa
-rw-r--r--  1 mengwong  staff   571B Jun 22  2020 id_rsa.pub
-rw-r--r--  1 mengwong  staff   5.8K Jan 21 21:19 known_hosts
-rw-------  1 mengwong  staff   1.7K Jul 23  2020 mengwong-sg-2.pem
-rw-------  1 mengwong  staff   1.7K Jun 22  2020 mengwong-sg-3.pem
```

the `id_rsa` file is a plain text file containing a private key – do you have it as a directory?

**Comment by maxloopinmok** [comment]
I've also tried to copy the SSH files under the id_rsa name, but the same error occurred:
```
cp /mnt/c/Users/maxloo/maxasus.pub ~/.ssh/id_rsa/id_rsa.pub
cp /mnt/c/Users/maxloo/maxasus ~/.ssh/id_rsa/id_rsa
cp /mnt/c/Users/maxloo/maxasus.pub ~/.ssh/id_rsa.pub
cp /mnt/c/Users/maxloo/maxasus ~/.ssh/id_rsa

```

**Comment by mengwong** [comment]
Right, after that you need to change the perms.

when I have multiple identities I use ssh-agent and ssh-add to make them all available.

**Comment by maxloopinmok** [comment]
I've edited my ~/.bashrc file to include ssh-agent and ssh-add as advised at:
[ssh keys ssh-agent bash and ssh-add](https://superuser.com/questions/284374/ssh-keys-ssh-agent-bash-and-ssh-add)

But the same error occurred.  I've also tried removing this file:
~/.ssh/known_hosts

Then, I tried cloning again:
git clone git@github.com:maxloosmu/haskellbook.git

What happens is that the system will display part of a RSA key fingerprint and ask me if I want to continue connecting.  I have 2 fingerprints in my Github account.  But the fingerprint shown is not either of them.. so when I tried to connect, the same error occurred...

**Comment by mengwong** [comment]
Have you tried using `ls -al` to look around the directory? Reality so frequently fails to live up to my expectations that I have learned never to miss an opportunity to catch it the act.

**Comment by maxloopinmok** [comment]
This is the directory listing of my new Windows PC's bash's ~/.ssh/ which I'm trying to connect to Github:

```
maxloo@MAXASUS:/mnt/c/Users/maxloo/src$ ls -al ~/.ssh/
total 4
drwx------ 1 maxloo maxloo 512 Feb  9 19:54 .
drwxr-xr-x 1 maxloo maxloo 512 Feb  9 16:56 ..
drwxr-xr-x 1 maxloo maxloo 512 Feb  9 19:17 id_rsa
-rwxr-xr-x 1 maxloo maxloo 397 Feb  9 19:24 id_rsa.pub
-rw-r--r-- 1 maxloo maxloo 884 Feb  9 19:54 known_hosts
```

**Comment by maxloopinmok** [comment]
I also had a look at my old Windows PC, which can push into Github, for some clues, but I could not access/copy README.txt and config:

```
max@MAXLEN:/mnt/c/WINDOWS/system32$ ls -al ~/.ssh/
total 16
drwx------ 1 max max  512 Sep 29 22:35 .
drwxr-xr-x 1 max max  512 Nov 20 17:05 ..
---------- 1 max max  273 Sep 30 01:29 README.txt
---------- 1 max max  113 Sep 30 00:29 config
-rw------- 1 max max 1679 Sep 29 22:35 id_rsa
-rw-r--r-- 1 max max  401 Sep 29 22:35 id_rsa.pub
-rw-r--r-- 1 max max 2910 Oct 27 22:21 known_hosts
---------- 1 max max 1766 Sep 29 22:41 maxssh
---------- 1 max max  401 Sep 29 22:41 maxssh.pub
```

**Comment by mengwong** [comment]
What happens when you `ssh git@github.com`? If that works you should be able to git clone the repo.

**Comment by mengwong** [comment]
Re the permissions, I think one of the missingsemester sessions covers chmod in the shell. http://zacheller.dev/missing-semester0

**Comment by mengwong** [comment]
It looks like `id_rsa` is a directory, so you should probably delete it and then try moving your private key file again to that path, and it should show up as a plain file this time.

**Comment by mengwong** [comment]
https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh has a generally good introduction, but i can totally understand how a weird situation with id_rsa being a directory could get you stuck … let's see if that helps?

**Comment by maxloopinmok** [comment]
Thanks, I removed the id_rsa directory and followed the instructions at https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh to resolve the issues.
